collections:
  lectures:
    output: true
    sort_by: ordering
  practicals:
    output: true
    sort_by: ordering
  extras:
    output: true

line1Title: INF03NA
# line2Title: Teoria da Computação e Introdução a Teoria de Autômatos
line2Title: Teoria da Computação
line3Title: 2022/1
tabTitle: Teoria da Computação.
warning: The materials are currently being updated for the next course edition.
smallNavbar: true
timeSpent: true
idleTimeout: 60

footerImage: ../images/tudelft-ewi-dark-footer.svg #the light-footer goes well with a light theme, the dark footer with a dark theme
headerImage: assets/images/fucapi.png.png
cssTheme: themes/light-grey.css
cssCodeTheme: themes/code/dracula.css

plugins:
  - jemoji
  - jekyll-remote-theme

markdown: kramdown
# !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
# Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)
highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: "highlight"
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true

baseurl: "/teoriaDaComputacao/"
remote_theme: chauff/cse-theme
